name: Specter
version: 0.4
author: Falkirks
main: specter\Specter
api: [3.0.0-ALPHA9]
softdepend: ["iControlU"]
commands:
  specter:
    usage: /specter <action> <player> [params]
    permission: specter.command
    aliases: ['s']
permissions:
  specter:
    default: op
    children:
      specter.command:
        default: op
